SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE DATABASE IF NOT EXISTS `[DB]` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `[DB]` ;
DROP TABLE IF EXISTS `[DB]`.`[PREFIX]settings` ;
CREATE TABLE IF NOT EXISTS `[DB]`.`[PREFIX]settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `language` VARCHAR(10) NOT NULL DEFAULT 'en',
  `categories` TEXT NULL,
  `customFields` TEXT NULL,
  `textColor` VARCHAR(7) NOT NULL DEFAULT '#7da800',
  `bgColor` VARCHAR(7) NOT NULL DEFAULT '#ffffff',
  `lastModify` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
CREATE UNIQUE INDEX `uuid_UNIQUE` ON `[DB]`.`[PREFIX]settings` (`uuid` ASC);
DROP TABLE IF EXISTS `[DB]`.`[PREFIX]events` ;
CREATE TABLE IF NOT EXISTS `[DB]`.`[PREFIX]events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calId` INT NOT NULL,
  `groupId` VARCHAR(32) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `recurring` VARCHAR(15) NULL,
  `category` VARCHAR(255) NULL,
  `custom` TEXT NULL,
  `dtstart` VARCHAR(50) NULL,
  `exdate` VARCHAR(255) NULL,
  `duration` VARCHAR(6) NULL,
  `rrule` VARCHAR(255) NULL,
  `start_event` VARCHAR(50) NOT NULL,
  `end_event` VARCHAR(50) NULL,
  `url` VARCHAR(255) NULL,
  `color` VARCHAR(20) NULL,
  `text_color` VARCHAR(20) NULL,
  `allday` TINYINT(1) NOT NULL,
  `lastModify` INT(11) NULL,
  PRIMARY KEY (`id`, `calId`),
  CONSTRAINT `fk_[PREFIX]events_settings`
    FOREIGN KEY (`calId`)
    REFERENCES `[DB]`.`[PREFIX]settings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
DROP TABLE IF EXISTS `[DB]`.`[PREFIX]users` ;
CREATE TABLE IF NOT EXISTS `[DB]`.`[PREFIX]users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(32) NULL,
  `lastLogin` INT(11) NULL,
  `lastModify` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
CREATE UNIQUE INDEX `id_UNIQUE` ON `[DB]`.`[PREFIX]users` (`id` ASC);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;